#!/usr/bin/env python
'''Config file for custom ee assets'''
import re

ds_settings = {
    'NOAA_CRN':  {
        'download_method': 'ftp',
        'ftp_server': 'ftp.atdd.noaa.gov',
        'ftp_folder': 'CI/crn/gridded/netCDF/archive/alldays/',
        'infile_ext': 'nc',
        'outpath': '/Volumes/DHS/NOAA_CRN/nc',
        'infile_fmt': '{var_name}_all.nc',
        'infile_dt_fmt': '%Y%m%d',
        'dat_nodata': 9.96921e+36,
        'bucket_name': 'gs://climate-engine',
        'bucket_folder': 'noaa_crn/daily',
        'asset_coll': 'projects/climate-engine/noaa_crn/daily',
        'asset_id_fmt': '{date}',
        'asset_dt_fmt': '%Y%m%d',
        'asset_proj': 4326,
        'asset_geo': [-125.10030746459961, 0.20061493, 0, 50.10067081451416, 0, -0.20134163],
        'asset_nodata': -9999,
        'asset_shape': (150, 325),
        'bands': {
            'AWC': 'AWC',
            'Fract_awc': 'FRACT_AWC',
            'Air_temp': 'AIR_TEMP',
            'Sur_temp_max': 'SUR_TEMP_MAX',
            'Sur_temp_min': 'SUR_TEMP_MIN',
            'Surface_temp': 'SUR_TEMP',
            'Temp_max': 'TEMP_MAX',
            'Temp_min': 'TEMP_MIN',
            'Precip': 'PRECIP',
            'Smois_05cm': 'SMOIS_05CM',
            'Smois_10cm': 'SMOIS_10CM',
            'Smois_20cm': 'SMOIS_20CM',
            'Smois_50cm': 'SMOIS_50CM',
            'Smois_100cm': 'SMOIS_100CM',
            'Soiltemp_05cm': 'SOILTEMP_05CM',
            'Soiltemp_10cm': 'SOILTEMP_05CM',
            'Soiltemp_20cm': 'SOILTEMP_05CM',
            'Soiltemp_50cm': 'SOILTEMP_05CM',
            'Soiltemp_100cm': 'SOILTEMP_05CM',
            'Solar': 'SOLAR_RADIATION',
            'Wind': 'WIND',
            'rh': 'RELATIVE_HUMIDITY'
        },
		'band_names': {
            'AWC': 'Available Water Capacity',
            'Fract_awc': 'Fractional Available Water Capacity',
            'Air_temp': 'Air Temperature',
            'Sur_temp_max': 'Maximum Surface Temperature',
            'Sur_temp_min': 'Minimum Surface Temperature',
            'Surface_temp': 'Surface Temperature',
            'Temp_max': 'Maximum Temperature',
            'Temp_min': 'Minimum Temperature',
            'Precip': 'Precipitation',
            'Smois_05cm': 'Soil Moisture at 5cm',
            'Smois_10cm': 'Soil Moisture at 10cm',
            'Smois_20cm': 'Soil Moisture at 20cm',
            'Smois_50cm': 'Soil Moisture at 50cm',
            'Smois_100cm': 'Soil Moisture at 100cm',
            'Soiltemp_05cm': 'Soil Temperature at 5cm',
            'Soiltemp_10cm': 'Soil Temperature at 10cm',
            'Soiltemp_20cm': 'Soil Temperature at 20cm',
            'Soiltemp_50cm': 'Soil Temperature at 50cm',
            'Soiltemp_100cm': 'Soil Temperature at 100cm',
            'Solar': 'Solar Radiation',
            'Wind': 'Wind',
            'rh': 'Relative Humidity'
        }
    }
}
